### PR TITLE
add projects using quic-go

### PR DESCRIPTION
**Pull request by geopinggg**

### CODE REVIEW

**Comment by gedw99** [comment]
You could add Caddy too btw

**Review by marten-seemann — APPROVED** [review]
Sorry for the long delay here. Can you please rebase the PR and sign the CLA, then I can merge it.

**Comment by geopinggg** [comment]
got problem on sign the CLA. I will close this PR and create a new one to complete CLA requirements.

**Comment by geopinggg** [comment]
Hi @marten-seemann, opened #3515 for this, please ignore this PR. Thanks.

**Pull request closed without merging**
