### PR TITLE
fix FreeBSD and DragonFly IP_RECVTOS undefined

### PR DESCRIPTION
**Pull request by kslr**
https://github.com/lucas-clemente/quic-go/issues/2880
https://github.com/v2fly/v2ray-core/pull/425

### CODE REVIEW

**Comment by marten-seemann** [comment]
This doesn't seem to work for dragonfly:
```
❯ GOOS=dragonfly go test
# github.com/lucas-clemente/quic-go [github.com/lucas-clemente/quic-go.test]
./conn_ecn.go:33:13: undefined: setRECVTOS
./conn_ecn.go:74:75: undefined: msgTypeIPTOS
FAIL	github.com/lucas-clemente/quic-go [build failed]
```

**Comment by marten-seemann** [comment]
Also, Freebsd seems to work without any modification (command run on `master`):
```
❯ GOOS=freebsd go test
fork/exec /var/folders/q0/b5ynf00142l7bl9sp8y098zr0000gn/T/go-build035224276/b001/quic-go.test: exec format error
FAIL	github.com/lucas-clemente/quic-go	0.002s
```

**Comment by kslr** [comment]
sorry, I only test it as a dependency.

Try to install a dragonfly(or other bsd).....

**Comment by marten-seemann** [comment]
I'm not talking about local tests. To merge this PR, we'll need automated tests (on CI).
This PR would have broken FreeBSD support, had I not checked it manually.

**Comment by kslr** [comment]
after investigating, I think ci can’t do this
```bash
# FreeBSD 12.2
root@freebsd-s-1vcpu-1gb-nyc1-01:~ # git clone https://github.com/kslr/quic-go.git
root@freebsd-s-1vcpu-1gb-nyc1-01:~ # wget https://golang.org/dl/go1.15.5.freebsd-amd64.tar.gz
root@freebsd-s-1vcpu-1gb-nyc1-01:~ # tar -C /usr/local -xzf go1.15.5.freebsd-amd64.tar.gz
root@freebsd-s-1vcpu-1gb-nyc1-01:~ # setenv PATH ${PATH}:"/usr/local/go/bin"
```

master
```bash
Running Suite: QUIC Suite
=========================
Random Seed: 1605601606
Will run 694 of 694 specs

••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••2020/11/17 08:26:49 Failed to increase receive buffer size: set udp 127.0.0.1:13579: setsockopt: no buffer space available
•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
------------------------------
• Failure [0.013 seconds]
Basic Conn Test
/root/2/quic-go/conn_ecn_test.go:17
  ECN conn
  /root/2/quic-go/conn_ecn_test.go:18
    reads ECN flags on IPv4 [It]
    /root/2/quic-go/conn_ecn_test.go:55

    Expected
        <protocol.ECN>: 0
    to equal
        <protocol.ECN>: 2

    /root/2/quic-go/conn_ecn_test.go:72
------------------------------
••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••

Summarizing 1 Failure:

[Fail] Basic Conn Test ECN conn [It] reads ECN flags on IPv4
/root/2/quic-go/conn_ecn_test.go:72

Ran 694 of 694 Specs in 30.759 seconds
FAIL! -- 693 Passed | 1 Failed | 0 Pending | 0 Skipped
--- FAIL: TestQuicGo (30.90s)
FAIL
exit status 1
FAIL	github.com/lucas-clemente/quic-go	30.919s
```

pr
```bash
Running Suite: QUIC Suite
=========================
Random Seed: 1605601150
Will run 694 of 694 specs

•••••••••••••••••••••••••••••••••••••••••••••••••••••••••2020/11/17 08:19:11 Failed to increase receive buffer size: set udp 127.0.0.1:13579: setsockopt: no buffer space available
•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
Ran 694 of 694 Specs in 26.488 seconds
SUCCESS! -- 694 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
ok  	github.com/lucas-clemente/quic-go	26.635s
```

dragonfly,  i'm looking for a way

**Comment by dentarg** [comment]
FYI https://cirrus-ci.org/features/ have FreeBSD and it seems to be free for open-source (I haven't tested it myself, but thought I should share the info anyway)

(I came here because I saw the `undefined: syscall.IP_RECVTOS` message while build [storj](https://github.com/storj/storj) on OpenBSD)

**Pull request closed without merging**
