### PR TITLE
gquic support VersionGQUICTLS

### PR DESCRIPTION
**Pull request by thinkboy**
gquic branch support a VersionGQUICTLS define in interface.go

### CODE REVIEW

**Comment by marten-seemann** [comment]
This is PR is wrong. gQUIC is not IETF QUIC.

**Comment by thinkboy** [comment]
@marten-seemann  So how to use TLS in gquic branch?  Or you mean gquic doesn`t support TLS?

**Comment by marten-seemann** [comment]
As explained in the README, the master branch has IETF QUIC support.

**Comment by thinkboy** [comment]
Please whether the TLS version is supported in the future with gQUIC branch？

Cause i saw a comment about gQUIC support in https://github.com/lucas-clemente/quic-go/issues/1645. So do you still maintaining the gQUIC branch, and still support new feature?

**Comment by jinleileiking** [comment]
Seems this project left gquic to a garbage can. Long time no update

**Comment by thinkboy** [comment]
> Please whether the TLS version is supported in the future with gQUIC branch？
> 
> Cause i saw a comment about gQUIC support in #1645. So do you still maintaining the gQUIC branch, and still support new feature?

@marten-seemann Can you reply to this question?

**Pull request closed without merging**
