### PR TITLE
Implement Spin Bit and VEC

### PR DESCRIPTION
**Pull request by ferrieux**
Hello. This implements the Spin Bit and Valid Edge Counter, as per section 4 of draft-trammell-quic-spin . Was made possible by the freeing of the two low-order bits of the flags byte by varint-packet-numbers (transport draft 12).

To exercise it and validate the result, take a pcap and submit it to our online spinbit+VEC analysis tool at http://193.252.113.227/cgi-bin/quicspin.cgi

Welcoming any comments/questions: alexandre.ferrieux@orange.com

### CODE REVIEW

**Comment by ferrieux** [comment]
I signed it ! (the CLA)

**Comment by ferrieux** [comment]
I updated my CLA with the proper e-mail address

**Comment by ferrieux** [comment]
CI randomly fails in "handshake drop tests / establishes a connection when 1/4 of the packets are lost in both direction". Looks like the overall test has a non-100% probability of success, independently from this PR. Do you confirm ?

**Comment by marten-seemann** [comment]
Hello, thank you for your PR!
Since the spin bit isn't part of the QUIC WG draft, I won't merge any spin-bit related PRs at this moment. Feel free to maintain a fork of quic-go and run experiments with it. 
If the spin bit ever becomes part of the core QUIC specification, we will decide at that point if quic-go will or will not enable support for this feature.

**Comment by ferrieux** [comment]
I understand, but please note that as of draft 12 these bits are reserved, so the PR in no way hampers interop, it just wastes a few CPU cycles, while it allows people to test the new feature in real life, feeding the debate for adoption. Chicken-and-egg. Also note that PicoQuic has just accepted it master.

**Pull request closed without merging**
