### PR TITLE
Fix Flushing of dead RoundTripper clients

### PR DESCRIPTION
**Pull request by heri16**
Auto-delete clients from RoundTripper with sessions that are dead/stale/done.
Issue #931

### CODE REVIEW

**Comment by heri16** [comment]
Tests are failing on Travis as [](https://quic.clemente.io/foobar.html) and [](https://quic.clemente.io/file1.html) no longer exists. What should be done?

**Comment by heri16** [comment]
I signed it!

**Comment by marten-seemann** [comment]
Hello @heri16, sorry for the late reply, I must have missed your PR somehow.

Deleting closed clients in the roundtripper is only the correct thing to do under one condition: when the connection was closed properly. There are a lot of cases where you don't want to delete the client: when the connection timed out because the peer didn't reply at all (i.e. it doesn't support QUIC), or when a protocol violation occurred.

**Comment by marten-seemann** [comment]
Closing this PR due to age. Feel free to open a new one.

**Comment by heri16** [comment]
Connection Migration does not work properly for me without an ability for the RoundTripper to delete clients with sessions that are dead. For example, when there is a NAT rebinding, using an existing client causes the connection to not be able to reestablish after a connection timeout.

**Comment by marten-seemann** [comment]
That's a known issue: #765.

**Pull request closed without merging**
