### PR TITLE
set the don't fragment (DF) bit on Windows

### PR DESCRIPTION
**Pull request by tobyxdd**

### CODE REVIEW

**Comment by marten-seemann** [comment]
Is there any way we can test this? I realize testing that DF is actually set might be difficult, but at least we should be able to pass a net.UDPConn to newConn and make sure it doesn’t return an error.

**Comment by tobyxdd** [comment]
Not sure what happened but it doesn't look related to my changes

**Review by marten-seemann — APPROVED** [review]
I haven't checked Wireshark to see if the DF bit is actually set. @tobyxdd, have you?

**Comment by tobyxdd** [comment]
Yes I did

**Comment by tobyxdd** [comment]
image
image

without vs with on Windows

**Review by marten-seemann — APPROVED** [review]
Thank you @tobyxdd!

**Comment by marten-seemann** [comment]
@tobyxdd Have you checked if this also works on IPv6? I was just working on an equivalent PR for OSX, and it looks like there are different syscalls for IPv4 and IPv6.

**Comment by marten-seemann** [comment]
Or am I misunderstanding something here? IPv6 shouldn't allow any packet fragmentation anyway, but then why is there a `unix.IPV6_DONTFRAG` (see https://pkg.go.dev/golang.org/x/sys/unix).

**Comment by tobyxdd** [comment]
Just realized that IPv6 does have fragmentation (as an extension header), but only at the source, not routers.

https://en.wikipedia.org/wiki/IPv6_packet#Fragment
https://tools.ietf.org/html/rfc3542
https://blog.apnic.net/2016/05/19/fragmenting-ipv6/

**Comment by tobyxdd** [comment]
So yes I guess we do need to set DF for IPv6 as well (or get local MTU from the system?)

**Comment by marten-seemann** [comment]
> So yes I guess we do need to set DF for IPv6 as well (or get local MTU from the system?)

I'm not sure. It depends on what happens when we try to send a too large packet. We'd need some way to feed that information back into the MTU discovery code. Getting the local MTU from the system and initializing the MTU discoverer with that seems like the safer option, but I'm not sure it's needed in practice, as our maximum packet size is below 1500 bytes anyway.

**Pull request merged**
