### PR TITLE
The channel errorChan never close, if it does, panics.

### PR DESCRIPTION
**Pull request by gabrielperezs**
Close the channel errorChan with a defer and added an atomic value to
ensure that it is not trying to write to a close channel.

### CODE REVIEW

**Comment by gabrielperezs** [comment]
@googlebot I signed it!

**Comment by marten-seemann** [comment]
@gabrielperezs Thank you for this PR!
Can you please elaborate what problem this PR is solving? Currently, the `errorChan` is never closed, so there's no way anything could panic here.

**Comment by marten-seemann** [comment]
@gabrielperezs Any updates on this?

**Comment by marten-seemann** [comment]
Closing due to inactivity.

**Pull request closed without merging**
