### PR TITLE
Close streams in streamsMap when connection closed

### PR DESCRIPTION
**Pull request by jared2501**
An attempt at fixing #1289.

### CODE REVIEW

**Comment by jared2501** [comment]
@marten-seemann - feel free to fork this change

**Comment by marten-seemann** [comment]
Thanks for the PR!
Why do you return a map on CloseWithError? I’d prefer to call closeForShutdown() in the respective streams map.

Regarding the generated code: Just edit the _generic.go and run go generate. This will generate all required code.

**Comment by jared2501** [comment]
I returned the items since the item is a `generic.Type` so we can't invoke any methods on it. Not sure if there's a better way to do this?

And thanks for the tip!

**Comment by marten-seemann** [comment]
Code generation sucks...
I’m not sur if it works, but did you try adding the close method to the generic.Type (e.g. by creating an interface that has this method and inherits generic.Type)?
If that works, this would give us a lot cleaner code.

**Comment by jared2501** [comment]
Hmm, unfortunately you can't do that ;(

This code in the generic map:

```
type closeableStream interface {
	item
	closeForShutdown(error)
}
```

Results in this generated code with an error:

image

**Comment by jared2501** [comment]
To be honest, having the close method return the list of closed streams doesn't seem that bad to me!

**Comment by marten-seemann** [comment]
I think it's not a good solution because 1. is violates the separation of concern (streams are created and should be closed in the same struct) and 2. it involves a lot of unnecessary allocations.

**Comment by jared2501** [comment]
Ah yeah I see, makes sense. Will play around with this a bit tonight. I
think perhaps I can make the streams inherit the interface and it will work
as you suggest.

**Comment by marten-seemann** [comment]
Hi @jared2501,

I gave it a try myself, and submitted a fix in #1295. The key change is redefining the `item`:
```go
type item interface {
    generic.Type
    closeForShutdown(error)
}
```
and to make sure, that this definition doesn't end up in any auto-generated files (by putting the definition in a separate file). 
As I said before, code generation sucks. This is so much effort to get it right, and it feels so unnatural. I wish there was another way to do that, but I don't see one.

**Comment by jared2501** [comment]
Thanks for that Marten! That solution looks much better. Maybe one day the
language will make this kind of thing easier :)

**Pull request closed without merging**
