### PR TITLE
implement spurious RTO detection

### LINKED ISSUE #687: Implement spurious RTO detection

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #687.

### CODE REVIEW

**Comment by jared2501** [comment]
So cool! Deployed this to a couple nodes in our LTE service mesh and have seen a considerable increase in throughput and consistency. Bumping the minRTOTimeout to 300ms still sees further improvements in consistency (for context, typical unloaded RTT is ~180ms).

**Comment by jared2501** [comment]
Actually, nevermind about the need to bump minRTOTimeout - was deploying an older version. Everything looks great after this!

image

**Comment by marten-seemann** [comment]
Hi @jared2501, thanks for sharing this data. My benchmark suite didn't show any performance impact of spurious RTO detection (because just randomly dropping a bunch of packets doesn't create spurious RTOs, I guess), so it is **really** helpful to get some real word data for these changes.

There will be a few more changes to loss recovery coming very soon, namely:
* TLP (#497)
* not allowing retransmissions to be sent when we're congestion limited (#1283)
* more accurate RTO timeout calculation (#1236)

I'd be interested to see the impact of these. Would be really cool if you could share some more metrics once those PRs are landed.

**Comment by jared2501** [comment]
Hey @marten-seemann - more than happy to! Will keep an eye out for those changes landing :) Hopefully I'll get around to #1258 in the meantime so that I can get you some good numbers.

**Pull request merged**
