### PR TITLE
changed: congestion control can be selected via the config

### PR DESCRIPTION
**Pull request by TobiasVi**
Issue #776

### CODE REVIEW

**Comment by TobiasVi** [comment]
I signed it!

**Comment by Nikolasel** [comment]
I signed it!

**Comment by Nikolasel** [comment]
Please rerun.

**Comment by TobiasVi** [comment]
I signed it!

**Comment by marten-seemann** [comment]
Hi @TobiasVi, thank you for this PR!
We're excited about trying new congestion control algorithms in QUIC, and implementing BBR (#341) has long been on our ToDo list.
However, the only reason we currently have Reno support is because we translated the congestion control code from Chromium to Go, and it contained this Reno flag. It's completely untested, and definitely not intended for production use.
Therefore, I'd rather not offer a config option as this point, but instead wait until we have BBR support.

**Pull request closed without merging**
