### PR TITLE
fix request cancelation gorouting leaking when client.RoundTrip() returns error

### PR DESCRIPTION
**Pull request by fbzhong**
The goroutine for Request Cancelation is started too early. When client.RounTrip() returns error, there is no way to quit that goroutine.
It's best to create `reqDone := make(chan struct{})` and start that goroutine before call `newResponseBody`. The caller could stop it by calling `res.Body.Close()`.

### CODE REVIEW

**Comment by marten-seemann** [comment]
LGTM. Can you please fix the tests?

**Comment by fbzhong** [comment]
Sure~

**Comment by marten-seemann** [comment]
@fbzhong Are you still trying to fix this?

**Comment by fbzhong** [comment]
@marten-seemann Sorry for late reply.
Sure I will fix it.

**Comment by marten-seemann** [comment]
The fix you had the first time was correct. Please revert to this state and just fix the test case.

**Comment by fbzhong** [comment]
Ok. Let me take a look.

**Comment by marten-seemann** [comment]
Closing due to age. Will fix it myself.

**Pull request closed without merging**
