### PR TITLE
add contexts to all blocking functions

### LINKED ISSUE #1915: No way to set a timeout/deadline for Listener.Accept()
Other than closing a connection, which makes it tricky to handle shutdowns.
Ideally Accept/Listen should take a context.

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #1915.

@AudriusButkevicius What do you think?

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Looks good, yet I wonder for the benefits of this for the async stuff.

**Comment by marten-seemann** [comment]
I'm not sure I understand what you mean. Can you elaborate?

**Comment by AudriusButkevicius** [comment]
You've added context support for non-blocking openstream et al, I wonder the benefit of those.

**Comment by marten-seemann** [comment]
I added a context for `Open{Uni}StreamSync`, which is blocking if the endpoint reached the peers stream limit. `Open{Uni}Stream` is non-blocking (and returns an error when no new stream can be opened at that moment).

**Comment by AudriusButkevicius** [comment]
But Open[Uni]Stream would never block right? What would be the purpose of of the context in that case? I guess cancellation?

**Comment by marten-seemann** [comment]
`Open{Uni}Stream` never blocks, and it doesn't take a context.

**Comment by AudriusButkevicius** [comment]
Sorry, I was looking at accept which does block and now does take a context. Lgtm.

**Comment by marten-seemann** [comment]
Ok, thanks for the feedback!

**Pull request merged**
