### PR TITLE
[WIP] Add send pacing

### PR DESCRIPTION
**Pull request by twdkeule**

### CODE REVIEW

**Comment by lucas-clemente** [comment]
Is this ready for review? I haven't taken a look yet, as it still has WIP in the title ;)

**Comment by twdkeule** [comment]
No, I don't have the time.
I haven't implemented the comment from #355 if you're wondering.
But I do plan to pick it up again (probably in september).

**Comment by lucas-clemente** [comment]
Okay, no rush :)

**Comment by marten-seemann** [comment]
Hi @twdkeule, what's the status of this PR? Do you need help anywhere?

I spent some time working on a decent benchmarking suite for quic-go (see the https://github.com/lucas-clemente/quic-go/tree/tcp-benchmark branch), which compares the transfer rate with a TLS/TCP transfer under a wide range of network conditions. I'm really curious to see how packet pacing will improve things here.

**Comment by twdkeule** [comment]
If I remember correctly, some integration tests were failing the last time I worked on this. I will see if I have pushed all my changes

**Comment by sean-** [comment]
Has there been any movement on this?

**Comment by twdkeule** [comment]
No. :disappointed:

**Comment by marten-seemann** [comment]
Obsoleted by #1097.

**Pull request closed without merging**
