### PR TITLE
implement Server.RequestContext

### PR DESCRIPTION
**Pull request by omz13**
Implement the equivalent of net/http's Server.ConnContext in http3

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Just to chime in since I've been looking for this to. This is entirely not the equivalent to stdlib and it'd be very disingenuous to commit to this feature and it behave this way.

In this implementation, this is happening per-request, not per-connection. The entire point of the ConnContext is to be one per connection.

**Comment by mattrobenolt** [comment]
To be clear, to do this correctly, this needs to be hooked much much sooner in the flow and ensure it's passed all the way through. This should be hooked as close to the Accept() call as is realistic.

**Comment by omz13** [comment]
> In this implementation, this is happening per-request, not per-connection. The entire point of the ConnContext is to be one per connection.

I made a mistake on the naming. So instead of mucking around with the context at the connection level, I could achieve what was necessary by mucking around at the request level. Naming and description updated so it should be clearer.

**Comment by mattrobenolt** [comment]
At this point, why not just use a middleware pattern and wrap the server handler?

Still going to strongly suggest instead of any of this, we just implement ConnContext correctly.

**Comment by omz13** [comment]
I've refactored how to solve my original issue... this PR is not the path I'm going to pursue anymore; it can be ignored

**Pull request closed without merging**
