### PR TITLE
Fix cookie test for Go1.9

### PR DESCRIPTION
**Pull request by lucas-clemente**
Sending this as a separate PR as #708 will probably take more time and I'd like 1.9 to be usable for dev.

### CODE REVIEW

**Comment by marten-seemann** [comment]
I don't see the point merging this as long as there is other stuff that doesn't work properly with Go 1.9.

**Comment by lucas-clemente** [comment]
It's a valid commit, I don't see why we should delay it. I generally use betas locally and this breaks my workflow; that should be reason enough.

**Comment by lucas-clemente** [comment]
Also, this simplifies local debugging ;)

**Comment by marten-seemann** [comment]
Fair enough. What's the problem with 1.9 anyway?

**Comment by marten-seemann** [comment]
Please check what's going on with the CIs before merging.

**Pull request merged**
