### PR TITLE
Update session.go

### PR DESCRIPTION
**Pull request by apmattil**
#3117, fix: do not divide again.
keepAliveInterval was already divided by two at processTransportParametersImpl()

### CODE REVIEW

**Comment by apmattil** [comment]
@googlebot I signed it!

**Comment by apmattil** [comment]
@googlebot I fixed it.

**Comment by marten-seemann** [comment]
Can you please clean up the commit history? Please also write a meaningful commit message.

**Comment by apmattil** [comment]
I'll do this again.

**Pull request closed without merging**
