### PR TITLE
fix comment

### PR DESCRIPTION
**Pull request by jinleileiking**

### CODE REVIEW

**Comment by marten-seemann** [comment]
CI is failing because our certificate expired. I'll ask @lucas-clemente to renew it. Might take a bit though.

**Comment by jinleileiking** [comment]
Any progress?

**Comment by marten-seemann** [comment]
As I said, this might take a while. I don't believe fixing a comment is really that urgent...

**Comment by marten-seemann** [comment]
gQUIC is deprecated now. Closing.

**Pull request closed without merging**
