### PR TITLE
Add Go module support

### LINKED ISSUE #1547: Add Go modules support
Add go modules support as a part of Go 1.11. Easy setup without GOPATH.

### PR DESCRIPTION
**Pull request by xyproto**
* Add `go.mod` and `go.sum`
* Use `go mod vendor` to vendor dependencies
* Should resolve #1547
* All tests pass

### CODE REVIEW

**Comment by marten-seemann** [comment]
Why does this add almost half a million LOC to the code base?

**Comment by xyproto** [comment]
@marten-seemann Because the dependencies are vendored.

**Comment by marten-seemann** [comment]
We're already vendoring our dependencies right now, so I'd like to understand where these *additional* 500k LOC come from.

**Comment by marten-seemann** [comment]
Neither. We currently have our complete set of dependencies vendored, so I don't expect adding Go mod support to add anything.

**Comment by xyproto** [comment]
The dependencies were also updated with `go get -u`, if that helps explain things?

**Comment by marten-seemann** [comment]
No way this could have added 500k.

**Comment by xyproto** [comment]
Well, then I'm afraid your expectations do not match what actually happened.

**Comment by xyproto** [comment]
```
% go version
go version go1.11.2 linux/amd64
```

**Comment by lucas-clemente** [comment]
I think the difference here is that you're also vendoring the test-only deps (I see ginkgo in there), which we currently aren't doing.

Anyway, this might be a misunderstanding of go modules, but why is vendoring even required at all when using modules?

**Comment by xyproto** [comment]
@lucas-clemente

Thank you for a measured response.

I have not specifically vendored the test dependencies, this was done automatically as part of `go mod init` / `go get -u` / `go mod vendor`.

Vendoring in general is not required, for any project. It's a matter of preference.

Some projects like to be able to build and test everything, even if dependencies are unavailable or projects are abandoned and removed from the web in the future, while other projects prefer not to.

If you prefer not to vendor dependencies, I can update this pull request to only add `go.mod` and `go.sum`.

**Comment by xyproto** [comment]
Got no reply in 14 days. Closing pull request.

**Pull request closed without merging**
