### PR TITLE
implement net.Error interface for stream deadline expiration errors

### LINKED ISSUE #741: implement the correct net.Error interface for deadline exceeded errors
As noted by @AudriusButkevicius in #579, the `errDeadline` should implement the `net.Error` interface, in order to be consistent with the behaviour of the `net.Conn`.

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #741.

### CODE REVIEW

**Comment by marten-seemann** [comment]
The tests are failing because of #750.

**Comment by lucas-clemente** [comment]
LGTM, but please document this in interface.go.

**Comment by marten-seemann** [comment]
What do you want to document there? Errors always need to be type-asserted anyway.

**Comment by lucas-clemente** [comment]
I'd like to document that the errors returned by Write / Read on timeout implement the net.Error interface, similar to net.Conn: https://golang.org/pkg/net/#Conn

**Comment by marten-seemann** [comment]
Oh, right, this needs to be documented for `Read` and `Write`, not the deadline calls.

**Comment by marten-seemann** [comment]
I added the documentation. @lucas-clemente, LGTY?

**Comment by lucas-clemente** [comment]
👍

**Comment by marten-seemann** [comment]
Does 👍 mean approved?

**Comment by lucas-clemente** [comment]
Yes, was on my phone and couldn't find the approval thingie…

**Pull request merged**
