### PR TITLE
refactor http3/roundtrip.go to be more clear

### PR DESCRIPTION
**Pull request by aviscode**
Signed-off-by: Avi Rosenberg <avrumi96@gmail.com>

### CODE REVIEW

**Comment by marten-seemann** [comment]
Please stop opening new PRs. This is the third time you’re opening a PR for exactly the same change.

**Comment by aviscode** [comment]
Because we had some problems with the other once this one is the right one
Why r u closing it ??

**Comment by marten-seemann** [comment]
Because I reviewed and approved your code, twice already. Really, there was no reason to close the other PRs. Please familiarize yourself with Git and GitHub.

**Comment by aviscode** [comment]
Ok sure
I'm sorry on this incident
Can we pls reopen the last one that is the right one ?

**Comment by marten-seemann** [comment]
I reopened #3658. Everything looks fine there :)

**Pull request closed without merging**
