### PR TITLE
 refactor  http3/roundtrip.go to be more clear

### PR DESCRIPTION
**Pull request by aviscode**

### CODE REVIEW

**Review by marten-seemann — APPROVED** [review]

**Comment by marten-seemann** [comment]
We'll need the CLA before we can merge this though.

**Comment by marten-seemann** [comment]
I don't think you need the last two commits, do you?

**Comment by aviscode** [comment]
Yes

**Review by marten-seemann — CHANGES_REQUESTED** [review]
I don't see why, can you please clean up the commit history?

**Pull request closed without merging**
