### PR TITLE
call OnPacket{Acked, Lost} with the bytes in flight prior to event

### PR DESCRIPTION
**Pull request by marten-seemann**
The congestion calls `OnPacketAcked` and `OnPacketLost` should be called with the bytes in flight **prior** to the congestion event, see https://cs.chromium.org/chromium/src/net/quic/core/congestion_control/tcp_cubic_sender_bytes.cc?type=cs&sq=package:chromium&l=128-148.

This leads to a significant speed up under loss conditions.

Before:
```
+----------------------------+----------------------------+--------------------------+--------------------------+
|                            | Chrome => TCP/HTTPS server | Chrome => quic-go server | quic-go client => server |
+----------------------------+----------------------------+--------------------------+--------------------------+
| 10ms RTT                   |               52.23 ± 8.98 |            29.84 ± 11.01 |             35.54 ± 4.51 |
| 10ms RTT, 0.5% packet loss |               44.21 ± 5.07 |              3.45 ± 0.17 |              2.18 ± 0.12 |
| 10ms RTT, 1% packet loss   |               37.74 ± 7.62 |              2.43 ± 0.07 |              1.53 ± 0.08 |
| 10ms RTT, 3% packet loss   |               19.63 ± 2.10 |              1.36 ± 0.03 |              0.86 ± 0.02 |
+----------------------------+----------------------------+--------------------------+--------------------------+
Based on 3 samples of 40 MB. All values in MB/s.
```

After:
```
+----------------------------+----------------------------+--------------------------+--------------------------+
|                            | Chrome => TCP/HTTPS server | Chrome => quic-go server | quic-go client => server |
+----------------------------+----------------------------+--------------------------+--------------------------+
| 10ms RTT                   |               52.97 ± 7.96 |             31.83 ± 8.15 |             23.90 ± 2.80 |
| 10ms RTT, 0.5% packet loss |               51.35 ± 4.33 |              3.77 ± 0.24 |              2.43 ± 0.05 |
| 10ms RTT, 1% packet loss   |               40.56 ± 3.38 |              2.55 ± 0.06 |              1.84 ± 0.09 |
| 10ms RTT, 3% packet loss   |               24.64 ± 1.22 |              1.37 ± 0.03 |              0.99 ± 0.03 |
+----------------------------+----------------------------+--------------------------+--------------------------+
Based on 3 samples of 40 MB. All values in MB/s.
```

### CODE REVIEW

**Comment by marten-seemann** [comment]
@jared2501: Do you see any difference in the throughput on your LTE connections?

**Comment by jared2501** [comment]
Hey @marten-seemann --

Put the latest master branch on one of our LTE connections and ran a bulk upload through it. Here's the UDP packets over time:

image

During that drop in the middle the flow is not application-limited - quic is limiting it for some reason (i.e. see the dorpped messages spike in the top graph). Haven't had a change to add the metrics from #1258 or run a full before/after test sorry.

**Comment by jared2501** [comment]
Not seeing that much of a different in sustained throughput before and after - going to revert to before this commit and see if I can see the drop in flow rate I described above.

**Comment by jared2501** [comment]
Also, not sure if that drop in flow above is related to this commit. Running both before and after this commit I can't reproduce this drop.

**Comment by marten-seemann** [comment]
If it was shorter, I'd say it's an actual RTO event, but one minute seems way too long for that.

**Pull request merged**
